<?php 
$themename = "Photorific";
$shortname = "t";

/* Get Pages into a drop-down list */
$pages_list = get_pages();
$getpagnav = array();
foreach($pages_list as $apage) {
	$getpagnav[$apage->ID] = $apage->post_title;
}

$options = array (
 
array( "name" => $themename." Options",
	"type" => "title"),
 

array( "name" => "General",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Blog Title or Logo",
	"desc" => "Choose if you want to use the blog title or a custom logo",
	"desc2" => "Display Logo",
	"desc3" => "Display Blog Title",
	"value" => "",
	"value2" => "1",
	"id" => "site_name",
	"type" => "radio"),
	
array( "name" => "Logo URL",
	"desc" => "If you selected 'Display Blog Title' above, enter the URL for your logo. If you don't enter it, the default theme logo will be used",
	"id" => "custom_logo",
	"type" => "text",
	"std" => ""),
	
array( "name" => "404 Error Message",
	"desc" => "Enter the message that you want to be displayed when a file is missing. It can be HTML",
	"id" => "404_error",
	"type" => "textarea",
	"std" => ""),
	
array( "name" => "Google Analytics Code",
	"desc" => "Enter your google analytics code.",
	"id" => "analytics",
	"type" => "textarea",
	"std" => ""),
	
	array( "type" => "close"),
array( "name" => "Homepage",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Homepage Image Only or Blog w/ Image",
	"desc" => "Select whether you want to display the homepage with the navigation and background image only, or with the blog as well.",
	"desc2" => "Image Only",
	"desc3" => "Blog Page",
	"value" => "",
	"value2" => "1",
	"id" => "homepage_blog",
	"type" => "radio"),
	
array( "name" => "Default Background Image",
	"desc" => "Enter the URL to the background image that you want pages to use by default if no custom background images are set for them. (Any pages/posts you create without setting background image URL(s), this image will be used by default, including on the homepage)",
	"id" => "default_bg_image",
	"type" => "text",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Homepage Slider Options",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Slideshow On/Off",
	"desc" => "Select if you want the homepage to display the slideshow in the background or use the default background image",
	"desc2" => "On",
	"desc3" => "Off",
	"value" => "",
	"value2" => "1",
	"id" => "slideshow_onoff",
	"type" => "radio"),
	
array(	"name" => "Start Slide",
	"desc" => "Start slide or random. (Random will either show the slide when a user visits the page, or will just show the default image with no slideshow)",
	"desc2" => "Start",
	"desc3" => "Random",
	"value" => "",
	"value2" => "1",
	"id" => "start_slide",
	"type" => "radio"),
	
array(	"name" => "Show Images Randomly",
	"desc" => "Select if you want the homepage slideshow to randomly display images or to display them in order.",
	"desc2" => "Yes",
	"desc3" => "No",
	"value" => "",
	"value2" => "1",
	"id" => "random_images",
	"type" => "radio"),
	
array(	"name" => "Pause Slideshow on Mouse Hover",
	"desc" => "Select if you want the homepage slideshow to pause if the user is hovering the background image",
	"desc2" => "Yes",
	"desc3" => "No",
	"value" => "",
	"value2" => "1",
	"id" => "pause_slideshow",
	"type" => "radio"),
	
array(	"name" => "Slideshow Transition effect",
	"desc" => "Select the transition effect you would like the slideshow to use.",
	"id" => "transition_effect",
	"options" => array('Fade', 'Slide Top', 'Slide Left', 'Slide Right', 'Carousel Right', 'Carousel Left'),
	"type" => "select",
	"std" => ""),

array( "name" => "Transition Time",
	"desc" => "Enter the time in milliseconds you want the transition to take (1000 = 1 second)",
	"id" => "transition_time",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Slide Interval",
	"desc" => "Enter the time in milliseconds you want each image/slide to take (1000 = 1 second)",
	"id" => "slide_interval",
	"type" => "text",
	"std" => ""),
	
array(	"name" => "Performance",
	"desc" => "Select the type of performance you would like the slideshow to have",
	"id" => "performance",
	"options" => array('Normal', 'Hybrid speed/quality', 'Optimize image quality', 'Optimize transition speed (firefox/IE, not webkit)'),
	"type" => "select",
	"std" => ""),
	
array(	"name" => "Keyboard Navigation",
	"desc" => "Select whether or not you would like to be able to use the arrow keys to change images",
	"desc2" => "On",
	"desc3" => "Off",
	"value" => "",
	"value2" => "1",
	"id" => "keyboard_nav",
	"type" => "radio"),
	
array(	"name" => "Image Protection",
	"desc" => "Disable dragging images and right clicks using JavaScript",
	"desc2" => "On",
	"desc3" => "Off",
	"value" => "",
	"value2" => "1",
	"id" => "image_protect",
	"type" => "radio"),
	
array( "type" => "close"),
array( "name" => "Header/Main Sidebar Settings",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Navigation Color Style",
	"desc" => "Choose from the white or black navigation style",
	"id" => "nav_style",
	"options" => array('Dark', 'White'),
	"type" => "select",
	"std" => ""),

array( "name" => "Sidebar/Header Opacity",
	"desc" => "Choose the opacity you want to use for the sidebar ( enter value from 0.1 - 1.0 (0.8 = default))",
	"id" => "sidebar_opacity",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Logo/Site Title Color",
	"desc" => "Select the color you would like to use for the site title.",
	"id" => "logo_color",
	"type" => "color",
	"std" => ""),
		
array( "name" => "Sidebar Navigation Link Color",
	"desc" => "Select the color you would like to use for the sidebar navigation links.",
	"id" => "nav_link_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Sidebar Navigation Link Subtext Color",
	"desc" => "Select the color you would like to use for the sidebar navigation subtext links.",
	"id" => "nav_subtext_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Navigation Link Divider/Bottom Border Color",
	"desc" => "Select the color uou would like to use for the divider that goes between the navigation links",
	"id" => "nav_divider_color",
	"type" => "color",
	"std" => ""),
	
array(	"name" => "Show/Hide Search On Main Sidebar",
	"desc" => "Choose whether or not you would like to display the search bar on the main header/sidebar.",
	"desc2" => "Show Search",
	"desc3" => "Hide Search",
	"value" => "",
	"value2" => "1",
	"id" => "show_search",
	"type" => "radio"),
	
array( "name" => "Sidebar Search Background Color",
	"desc" => "Select the color you would like to use for the search bar background color on the main sidebar.",
	"id" => "search_bg_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Sidebar Search Text Color",
	"desc" => "Select the color you would like to use for the search bar text color on the main sidebar.",
	"id" => "search_text_color",
	"type" => "color",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Page Color Settings",
	"type" => "section"),
array( "type" => "open"),
	
array( "name" => "Page Content Area Background Color",
	"desc" => "Select the background color you would like to use for the page content area",
	"id" => "page_content_bg_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Page Recent/Popular Posts Widget Border Color",
	"desc" => "Enter the color of the 4px border that goes around the post thumbnails when using the custom recent posts/popular posts widgets.",
	"id" => "widget_border_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Sidebar List Border/Divider Color",
	"desc" => "Select the color you want to use for the sidebar list border color.",
	"id" => "sidebar_list_border_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Page Content Area Text Color",
	"desc" => "Select the color you would like to use for the page content area text",
	"id" => "page_content_text_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Page Content Area Text Link Color",
	"desc" => "Select the color you would like to use for the page content area textlink color.",
	"id" => "page_text_link_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "H1 Heading Color",
	"desc" => "",
	"id" => "h1_color",
	"type" => "color",
	"std" => ""),
	
	array( "name" => "H2 Heading Color",
	"desc" => "",
	"id" => "h2_color",
	"type" => "color",
	"std" => ""),
	
	array( "name" => "H3 Heading Color",
	"desc" => "",
	"id" => "h3_color",
	"type" => "color",
	"std" => ""),
	
	array( "name" => "H4 Heading Color",
	"desc" => "",
	"id" => "h4_color",
	"type" => "color",
	"std" => ""),
	
	array( "name" => "H5 Heading Color",
	"desc" => "",
	"id" => "h5_color",
	"type" => "color",
	"std" => ""),
	
	array( "name" => "H6 Heading Color",
	"desc" => "",
	"id" => "h6_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Pagination Background Color",
	"desc" => "",
	"id" => "pagi_bg_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Pagination Current Color",
	"desc" => "",
	"id" => "pagi_current_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Pagination Link Color",
	"desc" => "",
	"id" => "pagi_link_color",
	"type" => "color",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Sidebar Color Settings",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Sidebar Text Color",
	"desc" => "Select the color you would like to use for the sidebar text.",
	"id" => "sidebar_text_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Sidebar Link Color",
	"desc" => "Select the color you would like to use for the sidebar links.",
	"id" => "sidebar_link_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Sidebar Link Hover Color",
	"desc" => "Select the color you would like to use for the sidebar links when they're hovered on.",
	"id" => "sidebar_link_hover",
	"type" => "color",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Blog Color Settings",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Blog Post Title (Link)",
	"desc" => "Select the color you would like to use for blog post titles (link).",
	"id" => "blog_title_color",
	"type" => "color",
	"std" => ""),
	
array( "name" => "Blog Post Title Link Hover",
	"desc" => "Select the color that you would like to show when the user hovers over the blog post title.",
	"id" => "blog_title_hover",
	"type" => "color",
	"std" => ""),

array( "name" => "Blog Post Title Color (For Post Page)",
	"desc" => "Select the color you want the blog title to be on the main blog post page (not link)",
	"id" => "blog_title_page",
	"type" => "color",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Font Settings",
	"type" => "section"),
array( "type" => "open"),
	
array(	"name" => "Font Family",
	"desc" => "Select the font-family you would like to use.",
	"id" => "font_family",
	"options" => array('Arial, Helvetica, Garuda, sans-serif', 'Verdana, Geneva, Kalimati, sans-serif', 'Lucida Sans Unicode, Lucida Grande, Garuda, sans-serif', 'Georgia, Nimbus Roman No9 L, serif', 'Tahoma, Geneva, Kalimati, sans-serif', 'Trebuchet MS, Helvetica, Jamrul, sans-serif', 'Times New Roman, Times, FreeSerif, serif'),
	"type" => "select",
	"std" => ""),
	
array(	"name" => "Headings Font Family",
	"desc" => "Select the font-family you would like to use for all headings (sidebar, content, portfolio titles, blog post titles, etc).",
	"id" => "heading_font_family",
	"options" => array('Bebas Neue', 'Franchise', 'Nevis', 'PTF Nordic Std', 'Myriad Pro', 'AW Conqueror Inline', 'League Gothic'),
	"type" => "select",
	"std" => ""),
	
array( "name" => "Pagination Font",
	"desc" => "Enter the font that you want to use for the page navigation.",
	"id" => "pagi_font",
	"options" => array('Arial, Helvetica, Garuda, sans-serif', 'Verdana, Geneva, Kalimati, sans-serif', 'Lucida Sans Unicode, Lucida Grande, Garuda, sans-serif', 'Georgia, Nimbus Roman No9 L, serif', 'Tahoma, Geneva, Kalimati, sans-serif', 'Trebuchet MS, Helvetica, Jamrul, sans-serif', 'Times New Roman, Times, FreeSerif, serif'),
	"type" => "select",
	"std" => ""),
	
array( "name" => "H1 Font Size",
	"desc" => "Font size for h1 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h1_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H2 Font Size",
	"desc" => "Font size for h2 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h2_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H3 Font Size",
	"desc" => "Font size for h3 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h3_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H4 Font Size",
	"desc" => "Font size for h4 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h4_size",
	"type" => "text",
	"std" => ""),

array( "name" => "H5 Font Size",
	"desc" => "Font size for h5 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h5_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "H6 Font Size",
	"desc" => "Font size for h6 headings in pixels only (enter the number of pixels only, nothing else)",
	"id" => "h6_size",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Main Font Size",
	"desc" => "Font size for the main text in pixels only (enter the number of pixels only, nothing else)",
	"id" => "font_size",
	"type" => "text",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Portfolio Options",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Portfolio Columns",
	"desc" => "Select the amount of columns you would like to use for the portfolio.",
	"id" => "portfolio_cols",
	"options" => array('One Column', 'Two Columns', 'Three Columns', 'Four Columns'),
	"type" => "select",
	"std" => ""),
	
array( "name" => "Portfolio Items Per Page",
	"desc" => "Enter the amount of portfolio items you would like to display on each page)",
	"id" => "max_portfolio",
	"type" => "text",
	"std" => "12"),
	
array( "type" => "close"),
array( "name" => "Gallery Options",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Gallery Columns",
	"desc" => "Select the amount of columns you would like to use for the gallery.",
	"id" => "gallery_cols",
	"options" => array('Two Columns', 'Three Columns', 'Four Columns'),
	"type" => "select",
	"std" => ""),
	
array( "name" => "Gallery Items Per Page",
	"desc" => "Enter the amount of gallery items you would like to display on each page)",
	"id" => "max_gallery",
	"type" => "text",
	"std" => "12"),
	
array( "type" => "close"),
array( "name" => "prettyPhoto (lightbox) Options",
	"type" => "section"),
array( "type" => "open"),

array( "name" => "Lightbox Theme",
	"desc" => "Enter the theme you would like to use for lightbox (prettyPhoto)",
	"id" => "lightbox_theme",
	"options" => array('Dark Rounded', 'Dark Square', 'Facebook', 'Light Rounded', 'Light Square'),
	"type" => "select",
	"std" => ""),
	
array(	"name" => "Show Title",
	"desc" => "Select whether or not you would like to display the lightbox title.",
	"desc2" => "Show Title",
	"desc3" => "Hide Title",
	"value" => "",
	"value2" => "1",
	"id" => "show_lb_title",
	"type" => "radio"),
	
array(	"name" => "Allow Resize",
	"desc" => "Select whether or not you would like to allow the user to view the full image size when lightbox is opened",
	"desc2" => "Allow",
	"desc3" => "Disallow",
	"value" => "",
	"value2" => "1",
	"id" => "allow_resize",
	"type" => "radio"),

array( "name" => "Opacity",
	"desc" => "Enter the opacity level you would like to use for the lightbox when opened (value between 0 and 1 - ex: 0.8)",
	"id" => "opacity",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Default Width",
	"desc" => "Enter the width (in pixels) you would like to use for default when prettyPhoto is opened (only if 'Allow Resize' is on)",
	"id" => "default_width",
	"type" => "text",
	"std" => ""),
	
array( "name" => "Default Height",
	"desc" => "Enter the height (in pixels) you would like to use for default when prettyPhoto is opened (only if 'Allow Resize' is on)",
	"id" => "default_height",
	"type" => "text",
	"std" => ""),
	
array( "type" => "close"),
array( "name" => "Footer Settings",
	"type" => "section"),
array( "type" => "open"),

array(	"name" => "Show/Hide Footer",
	"desc" => "Choose whether or not you would like to display the footer.",
	"desc2" => "Show Footer",
	"desc3" => "Hide Footer",
	"value" => "",
	"value2" => "1",
	"id" => "show_footer",
	"type" => "radio"),

array( "name" => "Footer Copyright Text",
	"desc" => "Font size for the main text in pixels only (enter the number of pixels only, nothing else)",
	"id" => "copyright",
	"type" => "textarea",
	"std" => ""),
	
	array( "type" => "close")
 
);
?>